import { FiArrowUpRight } from "react-icons/fi";

export const portfolioItems = [
  {
    id: 1,
    about: "NORDWOVEN is a contemporary furniture brand that blends Nordic minimalism, rooted in nature, functional and refined in craft. They needed a clear, modern identity to match their luxury craftsmanship and attract their ideal customers.",
    subtitle: "Industry: Furniture & Interior Design",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    results: "Developed a premium identity reflecting brand values, Strengthened internal and external brand alignment, Positioned to appeal to upscale modern home lovers",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We brought the brand to life with a Scandinavian-inspired visual identity, clear messaging, and a positioning strategy that elevated NORDWOVEN from just furniture to a lifestyle statement.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 2,
    about: "",
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 3,
    about: "Alvore is a fast-growing design studio that helps businesses transform their ideas into visual experiences. Their mission is to blend creativity with strategy to deliver high-impact branding and design solutions.",
    subtitle: "Industry: Creative / Design",
    duration: "1 week",
    imageMod1: "/images/alv1.png",
    imageMod2: "/images/alv2.png",
    highlights: "we developed a bold, elevated brand identity that reflects Alvore’s creative spirit and forward-thinking approach. From crafting a distinctive logo to shaping the tone of voice and visual direction, every element was built to set them apart in a competitive design space.",
    results: "Completed full brand identity in 7 days, Delivered a distinct visual system that aligned with the brand’s creative direction., Improved brand clarity and market positioning.",
    approach: "We believe no two brands are the same. Our process with Alvore was rooted in deep understanding and strategic thinking, tailored to their specific vision. We supported them throughout the project and provided ongoing guidance because for us, branding doesn’t end at delivery.",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 4,
    about: "Alvore is a fast-growing design studio that helps businesses transform their ideas into visual experiences. Their mission is to blend creativity with strategy to deliver high-impact branding and design solutions.",
    subtitle: "Industry: Creative / Design",
    duration: "1 week",
    imageMod1: "/images/alv1.png",
    imageMod2: "/images/alv2.png",
    highlights: "we developed a bold, elevated brand identity that reflects Alvore’s creative spirit and forward-thinking approach. From crafting a distinctive logo to shaping the tone of voice and visual direction, every element was built to set them apart in a competitive design space.",
    results: "Completed full brand identity in 7 days, Delivered a distinct visual system that aligned with the brand’s creative direction., Improved brand clarity and market positioning.",
    approach: "We believe no two brands are the same. Our process with Alvore was rooted in deep understanding and strategic thinking, tailored to their specific vision. We supported them throughout the project and provided ongoing guidance because for us, branding doesn’t end at delivery.",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 5,
    about: "NORDWOVEN is a contemporary furniture brand that blends Nordic minimalism, rooted in nature, functional and refined in craft. They needed a clear, modern identity to match their luxury craftsmanship and attract their ideal customers.",
    subtitle: "Industry: Furniture & Interior Design",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    results: "Strengthened internal and external brand alignment, Strengthened internal and external brand alignment, Positioned to appeal to upscale, modern home lovers",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We brought the brand to life with a Scandinavian-inspired visual identity, clear messaging, and a positioning strategy that elevated NORDWOVEN from just furniture to a lifestyle statement.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 6,
    about: "",
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 7,
    about: "",
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },

  {
    id: 8,
    about: "Alvore is a fast-growing design studio that helps businesses transform their ideas into visual experiences. Their mission is to blend creativity with strategy to deliver high-impact branding and design solutions.",
    subtitle: "Industry: Creative / Design",
    duration: "1 week",
    imageMod1: "/images/alv1.png",
    imageMod2: "/images/alv2.png",
    highlights: "we developed a bold, elevated brand identity that reflects Alvore’s creative spirit and forward-thinking approach. From crafting a distinctive logo to shaping the tone of voice and visual direction, every element was built to set them apart in a competitive design space.",
    results: "Completed full brand identity in 7 days, Delivered a distinct visual system that aligned with the brand’s creative direction., Improved brand clarity and market positioning.",
    approach: "We believe no two brands are the same. Our process with Alvore was rooted in deep understanding and strategic thinking, tailored to their specific vision. We supported them throughout the project and provided ongoing guidance because for us, branding doesn’t end at delivery.",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },

  {
    id: 9,
    about: "NORDWOVEN is a contemporary furniture brand that blends Nordic minimalism, rooted in nature, functional and refined in craft. They needed a clear, modern identity to match their luxury craftsmanship and attract their ideal customers.",
    subtitle: "Industry: Furniture & Interior Design",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    results: "Positioned to appeal to upscale, modern home lovers, Strengthened internal and external brand alignment, Positioned to appeal to upscale, modern home lovers",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We brought the brand to life with a Scandinavian-inspired visual identity, clear messaging, and a positioning strategy that elevated NORDWOVEN from just furniture to a lifestyle statement.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
];
