import { FiArrowUpRight } from "react-icons/fi";

export const portfolioItems = [
  {
    id: 1,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 2,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 3,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 4,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 5,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 6,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },
  {
    id: 7,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "WOUR NOW",
    image: "/images/p2.png",
    height: "550px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Email Marketing"],
    year: "2024",
    buttons: [
      { text: "Campaign Highlights", icon: <FiArrowUpRight size={20} /> },
      { text: "Social Media", icon: <FiArrowUpRight size={20} /> },
      { text: "Analytics Report", icon: <FiArrowUpRight size={20} /> },
    ],
  },

  {
    id: 8,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "ALVORE DESIGN STUDIO",
    image: "/images/p3.png",
    height: "800px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Web Design & Development", "Paid Ads", "Email Marketing"],
    year: "2023",
    buttons: [
      { text: "Shop The Store", icon: <FiArrowUpRight size={20} /> },
      { text: "Case Study", icon: <FiArrowUpRight size={20} /> },
      { text: "Product Gallery", icon: <FiArrowUpRight size={20} /> },
    ],
  },

  {
    id: 9,
    subtitle: "Branding",
    duration: "1 week",
    imageMod1: "/images/nord1.png",
    imageMod2: "/images/nord2.png",
    highlights: "Highlights",
    results: "Results",
    approach: "Our Approach",
    company: "NORDWOVEN",
    image: "/images/p1.png",
    height: "450px",
    description:
      "We delivered a unified marketing (online & offline) for a stronger brand & richer customer experience.",
    services: ["Branding", "Paid Ads", "Brand Strategy"],
    year: "2024",
    buttons: [
      { text: "View Branding Guide", icon: <FiArrowUpRight size={20} /> },
      { text: "See Website", icon: <FiArrowUpRight size={20} /> },
      { text: "Results & Metrics", icon: <FiArrowUpRight size={20} /> },
    ],
  },
];
